name: 'Extract Delimetered Value'
description: 'Extracts which unit tests to be run based on a PR request body.'
author: 'Peter Guest'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  input-string:
    description: "The string to be searched within."
    required: true
  delimiter:
    description: "The delimited characters to find the text between."
    required: true
  fail-no-match:
    description: "Indicates if we should exit wihtout code 0. Default = false"
    default: "false"
outputs:
  is-matched:
    description: 'Indicate if we found the delimiters and got a value.'
  result:
    description: 'The extracted text.'

