name: 'Extract Delimetered Value'
description: 'Extracts which unit tests to be run based on a PR request body.'
author: 'Peter Guest'
runs:
  using: 'node12'
  main: 'dist/index.js'
inputs:
  input-string:
    description: "The string to be searched within."
    required: true
  delimiter:
    description: "The delimited characters to find the text between."
    required: true

